name: Dotnet Build Test

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      working-directory: gen2-sample/csharp-tsi-gen2-sample/DataPlaneClient
      run: dotnet restore
    - name: Build
      working-directory: gen2-sample/csharp-tsi-gen2-sample/DataPlaneClient
      run: dotnet build --configuration Release --no-restore
    - name: Pack
      working-directory: gen2-sample/csharp-tsi-gen2-sample/DataPlaneClient
      run: dotnet pack --configuration Release --no-restore src/TimeSeriesInsightsClient.csproj